### PR TITLE
Adding support for iOS GCM

### PR DESCRIPTION
**Pull request by pavlospt**

### CODE REVIEW

**Comment by MuhammadReda** [comment]
@pavlospt I am afraid I can't get what this commit add. GCM means Google Cloud Messaging, I can't understand what "Adding support for iOS GCM" means.

**Comment by pavlospt** [comment]
https://developers.google.com/cloud-messaging/ios/client 

Things are progressing!

**Comment by MuhammadReda** [comment]
Indeed they are :). Many thanks for the link.
But, I believe lots of things need to get changed.
For example, the server URL has changed, "registration_ids" is now replaced with "to", and few more changes.

**Comment by pavlospt** [comment]
"registration_ids" is working fine, but to be able to push to iOS Devices you need the "notification" property to be set. So my pull request just adds this little thingy and you can use it with iOS Devices too. Later on you can add more stuff on it!

**Pull request merged**
